### ISSUE TITLE
Fix mithCors example errors

### ISSUE THREAD

**Issue by tajpouria** [JWebCoder/mith#16]
Getting the following error on running [mithCors examples](https://github.com/tajpouria/cors/tree/master/examples/mith) you added to cors, Is there any way to fix it?

```sh
error: TS2345 [ERROR]: Argument of type 'string | URL' is not assignable to parameter of type 'string'.
  Type 'URL' is not assignable to type 'string'.
  return new URL(url).pathname
                 ~~~
    at https://deno.land/std@0.53.0/path/win32.ts:911:18

TS2345 [ERROR]: Argument of type 'string | URL' is not assignable to parameter of type 'string'.
  Type 'URL' is not assignable to type 'string'.
  return new URL(url).pathname;
                 ~~~
    at https://deno.land/std@0.53.0/path/posix.ts:433:18

Found 2 errors.
```
I'm also tried :
```ts
import { Mith } from "https://deno.land/x/mith@v0.7.0/mod.ts";
import { Router } from "https://deno.land/x/mith_router@v0.2.0/mod.ts";

```
and it wasn't helpful!

Using:
deno 1.2.3
v8 8.6.334
typescript 3.9.2

**Comment by JWebCoder** [comment]
I've created a pull request under cors repo tajpouria/cors#19

**Comment by tajpouria** [comment]
@JWebCoder Thank you :)
